# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: push

jobs:
  complie:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - name: Compile main with Maven
      run: mvn compile
    - name: Compile test with Maven
      run: mvn test-compile
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    - uses: actions/upload-artifact@v2
      with:
        name: my-target
        path: target/
  
  test:
  
    needs: complie
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    - uses: actions/download-artifact@v2
      with:
        name: my-target
        path: target/
    - name: Test with Maven
      run: mvn surefire:test
    - uses: actions/upload-artifact@v2
      with:
        name: my-report
        path: target/surefire-reports/
  
  assemble:
  
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    - uses: actions/download-artifact@v2
      with:
        name: my-target
        path: target/
    - name: Assemble project
      run: mvn package
    - uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        name: my-target
        path: target/
    - uses: actions/upload-artifact@v2
      with:
        name: buildJar
        path: target/*.jar
    - uses: geekyeggo/delete-artifact@v1
      if: startsWith(github.ref, 'refs/tags/') != true
      with:
        name: my-target
  release:
    needs: assemble
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: my-target
        path: target/
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: my-target
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
