# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  complie:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - name: Compile main with Maven
      run: mvn compile
    - name: Compile test with Maven
      run: mvn test-compile
    - uses: actions/upload-artifact@v2
      with:
        name: my-target
        path: target/
  
  test:
  
    needs: complie
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - uses: actions/download-artifact@v2
      with:
        name: my-target
        path: target/
    - name: Test with Maven
      run: mvn surefire:test
    - uses: actions/upload-artifact@v2
      with:
        name: my-report
        path: target/surefire-reports/*.xml
  
  assemble:
  
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - uses: actions/download-artifact@v2
      with:
        name: my-target
        path: target/
    - name: Assemble project
      run: mvn package
    - uses: actions/upload-artifact@v2
      with:
        name: my-target
        path: target/
    - uses: actions/upload-artifact@v2
      with:
        name: my-package
        path: target/*.jar
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: assemble
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: my-target
        path: target/
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
